"""
Layer 0 — Feature Store

Provides versioned pre-computed and on-the-fly features.
All features are version-stamped so every decision record can be debugged post-hoc.

Production note: swap _user_profiles / _merchant_profiles / _welford dicts
with Redis HGET/HSET calls for horizontal scaling.
"""
import math
import time
from dataclasses import dataclass
from typing import Dict, Optional

from .models import Transaction, FeatureVector

FEATURE_STORE_VERSION = "1.0.0"


"""
GRAPH FEATURES STARTUP LOADING (from data/graph_features.csv)
==============================================================
At application startup, load the PaySim-derived graph features into the feature
store to serve graph_distinct_accounts_1hr for real-time scoring.

How to load at startup (add to your application init / main entrypoint):

    import pandas as pd

    GRAPH_FEATURES_PATH = "data/graph_features.csv"

    # Load pre-computed graph features from PaySim simulation
    # Columns: nameOrig, step, graph_distinct_accounts_1hr,
    #          graph_outflow_amt_1hr, graph_tx_count_1hr, isFraud
    graph_df = pd.read_csv(GRAPH_FEATURES_PATH)

    # Build a lookup dict keyed by (nameOrig, step) for O(1) retrieval:
    #   key  = (account_id_str, step_int)  where step = unix_time // 3600
    #   value = dict of graph feature values
    graph_lookup = {
        (row["nameOrig"], int(row["step"])): {
            "graph_distinct_accounts_1hr": int(row["graph_distinct_accounts_1hr"]),
            "graph_outflow_amt_1hr": float(row["graph_outflow_amt_1hr"]),
            "graph_tx_count_1hr": int(row["graph_tx_count_1hr"]),
        }
        for _, row in graph_df.iterrows()
    }

    # Inject into the FeatureStore instance at startup:
    feature_store = FeatureStore()
    feature_store._graph_lookup = graph_lookup

    # In FeatureStore.extract_features(), retrieve graph features like:
    #   step = transaction.unix_time // 3600
    #   graph_data = self._graph_lookup.get(
    #       (str(transaction.cc_num), step), {}
    #   )
    #   graph_distinct_accounts_1hr = graph_data.get("graph_distinct_accounts_1hr", 0)

    # NOTE: For production, replace the dict lookup with a Redis HGET call
    # keyed as "graph:{account_id}:{step}" for horizontal scaling.
    # The graph_features.csv file is regenerated by scripts/step5_graph_features.py
    # and should be refreshed whenever the PaySim simulation data is updated.
"""


@dataclass
class WelfordState:
    """O(1) online mean and variance tracker (~100 bytes per user)."""
    n: int = 0
    mean: float = 0.0
    M2: float = 0.0  # sum of squared deviations from running mean

    def update(self, x: float):
        self.n += 1
        delta = x - self.mean
        self.mean += delta / self.n
        self.M2 += delta * (x - self.mean)

    @property
    def variance(self) -> float:
        return self.M2 / (self.n - 1) if self.n >= 2 else 0.0

    @property
    def std(self) -> float:
        return math.sqrt(self.variance)

    def zscore(self, x: float) -> float:
        return (x - self.mean) / self.std if self.std > 0 else 0.0


class FeatureStore:
    VERSION = FEATURE_STORE_VERSION

    def __init__(self, redis_client=None):
        self._redis = redis_client
        self._welford: Dict[str, WelfordState] = {}
        self._user_profiles: Dict[str, Dict] = {}
        self._merchant_profiles: Dict[str, Dict] = {}
        self._graph_features: Dict[str, Dict] = {}
        self._last_txn_time: Dict[str, float] = {}
        self._ewma_scores: Dict[str, float] = {}

    # ------------------------------------------------------------------
    # Welford baseline
    # ------------------------------------------------------------------

    def _get_welford(self, user_id: str) -> WelfordState:
        if user_id not in self._welford:
            self._welford[user_id] = WelfordState()
        return self._welford[user_id]

    def update_welford(self, user_id: str, amount: float):
        self._get_welford(user_id).update(amount)

    def get_welford_state(self, user_id: str) -> WelfordState:
        return self._get_welford(user_id)

    def get_user_txn_count(self, user_id: str) -> int:
        return self._get_welford(user_id).n

    def get_amount_zscore(self, user_id: str, amount: float) -> float:
        return self._get_welford(user_id).zscore(amount)

    # ------------------------------------------------------------------
    # Account / merchant age
    # ------------------------------------------------------------------

    def get_days_since_account_open(self, user_id: str) -> int:
        ts = self._user_profiles.get(user_id, {}).get("account_open_ts", time.time())
        return int((time.time() - ts) / 86400)

    def get_merchant_active_days(self, merchant_id: str) -> int:
        ts = self._merchant_profiles.get(merchant_id, {}).get("first_seen_ts", time.time())
        return int((time.time() - ts) / 86400)

    # ------------------------------------------------------------------
    # Last-transaction time
    # ------------------------------------------------------------------

    def update_last_txn_time(self, user_id: str):
        self._last_txn_time[user_id] = time.time()

    def get_time_since_last_txn(self, user_id: str) -> float:
        last = self._last_txn_time.get(user_id)
        return float("inf") if last is None else time.time() - last

    # ------------------------------------------------------------------
    # EWMA fraud score
    # ------------------------------------------------------------------

    def get_ewma_score(self, user_id: str) -> float:
        return self._ewma_scores.get(user_id, 0.0)

    def update_ewma_score(self, user_id: str, new_score: float, alpha: float = 0.3):
        prev = self._ewma_scores.get(user_id, new_score)
        self._ewma_scores[user_id] = alpha * new_score + (1 - alpha) * prev

    # ------------------------------------------------------------------
    # Pre-computed feature bundle
    # ------------------------------------------------------------------

    def get_precomputed_features(self, user_id: str, merchant_id: str) -> Dict:
        user = self._user_profiles.get(user_id, {})
        merch = self._merchant_profiles.get(merchant_id, {})
        graph = self._graph_features.get(merchant_id, {})
        return {
            "spend_30d_by_category": user.get("spend_30d_by_category", {}),
            "velocity_buckets": user.get(
                "velocity_buckets", {"1min": 0, "10min": 0, "1hr": 0, "24hr": 0}
            ),
            "days_since_account_open": self.get_days_since_account_open(user_id),
            "device_history_hash": user.get("device_history_hash", ""),
            "merchant_txn_volume_per_hr": merch.get("txn_volume_per_hr", 0.0),
            "merchant_chargeback_rate_30d": merch.get("chargeback_rate_30d", 0.0),
            "merchant_fraud_signal_index": merch.get("fraud_signal_index", 0.0),
            "graph_distinct_accounts_1hr": graph.get("distinct_accounts_1hr", 0),
            "graph_shared_device_flagged": graph.get("shared_device_flagged", False),
        }

    # ------------------------------------------------------------------
    # Full feature vector assembly
    # ------------------------------------------------------------------

    def build_feature_vector(self, txn: Transaction) -> FeatureVector:
        """Combines pre-computed and on-the-fly features into a versioned vector."""
        user_id = str(txn.cc_num)
        merchant_id = txn.merchant
        pc = self.get_precomputed_features(user_id, merchant_id)
        vb = pc["velocity_buckets"]

        # On-the-fly: device fingerprint entropy (Shannon entropy of fingerprint bytes)
        fp = (txn.device_fingerprint or "unknown").encode()
        unique_bytes = set(fp)
        total = len(fp)
        entropy = -sum(
            (fp.count(bytes([b])) / total) * math.log2(fp.count(bytes([b])) / total)
            for b in unique_bytes
            if fp.count(bytes([b])) > 0
        )

        return FeatureVector(
            version=self.VERSION,
            user_spend_30d_by_category=pc["spend_30d_by_category"],
            velocity_1min=vb.get("1min", 0),
            velocity_10min=vb.get("10min", 0),
            velocity_1hr=vb.get("1hr", 0),
            velocity_24hr=vb.get("24hr", 0),
            days_since_account_open=pc["days_since_account_open"],
            device_history_hash=pc["device_history_hash"],
            merchant_txn_volume_per_hr=pc["merchant_txn_volume_per_hr"],
            merchant_chargeback_rate_30d=pc["merchant_chargeback_rate_30d"],
            merchant_fraud_signal_index=pc["merchant_fraud_signal_index"],
            graph_distinct_accounts_1hr=pc["graph_distinct_accounts_1hr"],
            graph_shared_device_flagged=pc["graph_shared_device_flagged"],
            amount_zscore=self.get_amount_zscore(user_id, txn.amt),
            time_since_last_txn=self.get_time_since_last_txn(user_id),
            country_ip_consistent=(txn.ip_country == ""),
            device_fingerprint_entropy=entropy,
        )
